### ISSUE TITLE
Segmentation Fault after changing map.

### ISSUE THREAD

**Issue by MaNaReaver** [gtteamamxx/Tower-Defense#22]
I had recently added the mod onto my ReHLDS server, and it loaded successfully on the first change, however, when the map is changed, the server crashes due to segmentation fault. I'm worried because that's preventing me from adding it permanently to my server. I love your mod, and can't wait to play it with others! Thanks and best regards.

**Comment by gtteamamxx** [comment]
Hello.

Thanks for contact.

Unfortunly didn't tested this mod on ReHLDS servers so I can't tell you what is wrong. Please add additional logging at plugin_end or try to disable one by one plugins and check if problem still exist.

I think it's problem with your configuration because there is already exist some polish server with this mod. I played there some times ago and server did not crash.
https://www.gametracker.com/server_info/51.83.241.195:27240/
