### ISSUE TITLE
Some error  in td_gunmod.amxx

### ISSUE THREAD

**Issue by talibanaa** [gtteamamxx/Tower-Defense#23]
L 10/18/2021 - 21:17:46: Player 1 is not in game.
L 10/18/2021 - 21:17:46: [AMXX] Displaying debug trace (plugin "td_gunmod.amxx", version "1.1")
L 10/18/2021 - 21:17:46: [AMXX] Run time error 10: native error (native "menu_display")
L 10/18/2021 - 21:17:46: [AMXX]    [0] td_gunmod.sma::showWeaponMenu (line 541)
L 10/18/2021 - 21:17:46: [AMXX]    [1] td_gunmod.sma::playerSpawned (line 298)

And im use the last rehlds amxx regame and server crash sometimes ? When will be see version 2.0 ot that mod! Thanks

**Comment by gtteamamxx** [comment]
Hi @talibanaa, 
Thanks for contact.

Unfurtunly I'm unable to check this issue at runtime right now, but if you look at source code

https://github.com/gtteamamxx/Tower-Defense/blob/87f5f791dc55ae2085246e264fba796c013e5d75/addons/amxmodx/scripting/td_gunmod.sma#L296-L301

We can assume that the issue is because this method:
`L 10/18/2021 - 21:17:46: [AMXX] [0] td_gunmod.sma::showWeaponMenu (line 541)`

is invoked by this line of code
 https://github.com/gtteamamxx/Tower-Defense/blob/87f5f791dc55ae2085246e264fba796c013e5d75/addons/amxmodx/scripting/td_gunmod.sma#L300
 
 You see that magic `0.5`? It tells "open weapon menu after 0.5 seconds of player spawn".
 
 And it looks like target player just disconnected in that 0.5s.
 
 To fix that we could add a validation to method which throws error `showWeaponMenu `
 
https://github.com/gtteamamxx/Tower-Defense/blob/87f5f791dc55ae2085246e264fba796c013e5d75/addons/amxmodx/scripting/td_gunmod.sma#L502-L510

There's missing
```cpp
if (!is_user_connected(id)) {
   return;
}
```

This error is not affecting a game - low priority bug. Server crashes - yeah, are caused by this mod but after some investigations year or two ago I'm 100% sure it's because this mod is maintaining high amount of entities and even on ReHLDS old GoldSrc engine can't stand that so it restarts. Maybe you can try to change monsters count on wave to 10-15 max.

I don't think there would be version 2.0. I was 16-18 with my twin brother when we created this mod. Nowadays we're professional programmers, oldest, and I don't think we have time to play games :D

Maybe in future :) 

Thanks for playing this mod. 
Cheers
